hpc/mpifileutils

- AUTHORS
- src/dcp2/dcp2.c
The list of ranks sending us work is not necessarily sequential, treating it as such leads to hung processes awaiting messages that will never be sent. This is especially prevalent as the number of ranks increases.
> Build the actual list of ranks to receive work from in dcp2

- doc/markdown/dstripe.1.md
- src/dstripe/dstripe.c
Number of improvements to dstripe in this pull request. List below.
- Add a --report flag to display file stripe size and stripe count
- Make stripe count and stripe size optional by giving them reasonable defaults
- No longer require that an output file path be provided
- Lay the ground work for a verbose flag (this can use further work)
- Update the documentation to reflect the new state of the tool
> dstripe Improvements

- AUTHORS
- doc/markdown/dstripe.1.md
- src/dstripe/dstripe.c
dstripe is now able to accept a list of paths as input. It will walk the paths provided and generate a list of files to restripe. The `-s` (stripe size) and `-c` (stripe count) can now be used to filter down the list of files found during the walk. Files that are left over are restripe candidates. 
Also replaced the old lustre api calls with the much cleaner llapi_layout.
TODO: Need to update the docs. I'll update this pull request with that soon.
> Re-work dstripe to restripe files found during path walking

- doc/markdown/dstripe.1.md
- src/dstripe/dstripe.c
Introduce a -m/--minsize option to allow users
to filter out files that are below a certain
file size. Users will most likely want to restripe
larger files.
> Add min file size filter to dstripe

- doc/markdown/dstripe.1.md
- src/dstripe/dstripe.c
Enable dstripe to print a file's size when using the
--report/-r option.
@adammoody I think the report option might be producing too much text. Do you have a preferred format to print a files info? I can incorporate it into this PR.
> dstripe's report option should print file size

- src/dstripe/dstripe.c
While filtering a list of files in dstripe, if a file
is not part of a lustre file system, simply skip it
for now.
I figure skipping the file would be appropriate since
we can't obtain lustre striping information and it clearly
states in the man pages that this tool only works for
lustre files. If it doesn't show up in the report, then
it should be assumed it's not a candidate for restripe.
Thoughts on that?
> Handle non-Lustre files gracefully in dstripe

- src/dcmp/dcmp.c
* added code to dcmp_strmap_compare_data & dcmp_compare_data to track whether or not the open file/reading errors were on the src or dest side
> adding code to track if read error was on src or dest side

- css/min.css
- index.html
Tweak css so the mpiFileUtils doesn't wrap on
index.html.
Closes #82
> Resolve wrapping of mpiFileUtils on homepage

- src/common/mfu_flist.h
- src/common/mfu_flist_copy.c
- src/dcp/dcp.c
[2017-09-28T14:49:37] [0] [../../../src/dcp/dcp.c:179] Using input list.
[2017-09-28T14:49:37] [0] [../../../src/dcp/dcp.c:157] Debug level set to: debug
[2017-09-28T14:49:37] [0] [../../../src/dcp/dcp.c:185] Preserving file attributes.
Usage: dcp [options] source target
dcp [options] source ... target_dir
Options:
-i, --input <file>  - read source list from file
-p, --preserve      - preserve permissions, ownership, timestamps, extended attributes
-s, --synchronous   - use synchronous read/write calls (O_DIRECT)
-S, --sparse        - create sparse files when possible
-v, --verbose       - verbose output
-h, --help          - print usage
> dcp runs against input flist is broken now

- src/Makefile.am
- src/common/mfu_flist.c
- src/common/mfu_flist.h
- src/dcmp/dcmp.c
dcmp: add permission comparison support
-o PERM=DIFFER...
> dcmp: add permission comparison support

- src/Makefile.am
commit ff71ec4605b084575e6bed507eaa7e6ac244a2f3 deleted dstripe from Makefile.am
(by mistake), here added it back.
> Addback dstripe to Makefile which deleted by mistake

- src/common/mfu_flist_copy.c
https://github.com/hpc/mpifileutils/issues/94
As on lustre, when the file closed, the data may not be synced to
backend immediately, so if update the timestamps during this gap,
that may cause the timestamps mismatch finally, so we add a force
sync after data copy, before we setting timestamps on the dest files,
to avoid this potential issue.
> mfu common: Append a force sync after data copy

- src/dcmp/dcmp.c
if (dcmp_option_need_compare(DCMPF_PERM)) {
dcmp_compare_field(ctime, DCMPF_PERM);
}
It's typo here, permission compare should compare the perm filed,
not the ctime, correct it here.
> dcmp: correct the call function of permission compare

- src/common/mfu_flist_copy.c
- src/common/mfu_param_path.c
Add pure mode support pure mode, e.g. if src ends with trailing slash, don't create additional
directory level at the destination, just copy sub dirs/files under src, similar to "rsync /foo/bar/ /foo1/".
> dcp: add pure copy mode support

- src/common/mfu_flist_io.c
Skip the output dump if no itmes in the list, otherwise it will crash like following:
sending incremental file list
sent 31937 bytes  received 160 bytes  64194.00 bytes/sec
total size is 27350230  speedup is 852.11
Files which have different modification times, number: 0/0
dcmp works properly, but it fails if it dumps to file if there are nothing differ
*** An error occurred in MPI_Type_get_extent
*** reported by process [139900657664001,0]
*** on communicator MPI_COMM_WORLD
*** MPI_ERR_TYPE: invalid datatype
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
> mfu: skip the output dump if no items in the list

- m4/lx_find_lustre.m4
- src/dstripe/dstripe.c
Correct lx_find_lustre.m4 to properly check for
header files. Also check that 'llapi_layout_alloc' is
a function in the Lustre API because dstripe currently
depends on it.
> Correct detection of Lustre API

- m4/lx_find_lustre.m4
- src/dstripe/dstripe.c
Lustre 2.5 is still a widely used version of Lustre. Introduce
support for Lustre 2.5 APIs since llapi_layouts were not introduced
until 2.7.
This is currently untested. I am attempting to find a way to test it.
> Introduce Lustre 2.5 support

- src/common/mfu_flist_copy.c
Add check to verify that user is syncing directories when deciding
whether or not to skip destination directory creation. We can assume
the destination directory exists only in the case that the sync
option is being used.
> fix for case where target directory does not exist

- src/dcp/dcp.c
The do_sync variable was not being initialized to zero by default,
which would cause undefined behavior. Also, the sparse variable
was being initialized to zero by default, but it should be a
boolean type based on how the struct was specified.
> fix initialization of do_sync and sparse variables in dcp

- src/common/mfu_flist.c
- src/common/mfu_flist.h
- src/dcmp/dcmp.c
Here are some minor improvements for dcmp.
"dcmp: improve the usage() 
dcmp: print the matched count of each conjunctions group in summary"
These two are used to improve the usage and summary log, in order to make it more friendly to users.
"dcmp: record the rawtime directly rather than converting from wtime"
This patch uses localtime() to record the time rather than MPI_Wtime (with additional conversion), to avoid some unexpected condition, e.g. time overflow.
"dcmp: skip the size differ check for dir"
This commit remove the size differ check for dir, as we are focusing the size check of files, not dirs, and on the other hand, size of dir may be different even contained files are the same, depends on the fs.
Please refer to the commits for details.
> Dcmp improve

- src/common/mfu_flist.c
- src/common/mfu_flist.h
- src/dcmp/dcmp.c
ACL(Access Control List) is widely used in modern file-systems, to support advanced
management.
So here we add a new comparison option named 'ACL' (-o ACL=DIFFER...) to support the ACL
comparison.
Following is a sample to use this feature:
```
getfacl: Removing leading '/' from absolute path names
user::rw-
user:ntp:rwx
group::r--
mask::rwx
other::r--
getfacl: Removing leading '/' from absolute path names
user::rw-
user:ntp:rwx
group::r--
mask::rwx
other::r--
Files which have different Access Control Listss: [0/0]
ACLs are the same, so no diff found.
change the ACL of file_2 and run dcmp again:
getfacl: Removing leading '/' from absolute path names
user::rw-
user:rpc:rwx
user:ntp:rwx
group::r--
mask::rwx
other::r--
Files which have different Access Control Listss: [1/1]
dcmp detected the …
```
> dcmp: add ACL comparison support

- src/dchmod/dchmod.c
When using a+r for instance, dchmod was incorrectly parsing this
as something that specified no letter (i.e +r), which uses umask.
This was causing dchmod to incorrectly assign permissions when
using the "all" attribute.
> Fix parse error in dchmod

- src/dcp/dcp.c
This prints a message about invalid src/dest paths when one or the
other is not provided. Also, the exit run and error is not printed
when only "help" is used.
> Add error reporting for missing src/dest paths in dcp

- experimental/dsh/dsh.c
- src/dcmp/dcmp.c
- src/dwalk/dwalk.c
Text output feature has been landed, let's make use of it, change text
to the default output format, and another option '-r/--raw' is introduced to
enable original native format.
> make use of text output fucntion

- src/common/mfu_flist_copy.c
Add a barrier between copying data and setting metadata, to make sure the
content update is synced before we start to set metadata, to avoid some metadata
mismatch problem, e.g. wrong modify timestamp.
> dcp: add a barrier between copying data and setting metadata

- src/common/mfu_flist_copy.c
Move link's ownership, permissions, and timestamps setting later into
mfu_copy_set_metadata, and now the link's timestamp will be synced up
if option preserve enabled, the same as we do to files.
> mfu: move link's attributes set into mfu_copy_set_metadata

- experimental/dsh/dsh.c
- src/common/mfu_flist.h
- src/common/mfu_flist_remove.c
- src/dcmp/dcmp.c
- src/drm/drm.c
Add traceless mode support to drm (-T/--traceless), if the option is enabled,
unlink file/dir/link will not change its parent dir's timestamp (atiem/mtime),
it is useful if some guy want to remove the extra files under dst dir after
a dcp, but not change the timestamp of the dst filesystem tree, in order to
keep the same as src.
> drm: add traceless mode support

- src/common/mfu_io.c
Technically speaking when calling readdir() "If  the  end  of  the
directory stream is reached, NULL is returned and errno is not changed."
Therefore if we want to test errno, we need to properly initialize it to zero
before calling readdir().
> Set errno = 0 before calling readdir()

- src/dsync/dsync.c
Here we add two new options to dsync:
-n/--dry-run, used to support dry-run mode, similar to dcmp if enabled. It should be helpful to users, who want to estimate the workload before doing the real syncing job.
-N/--no-delete, used to support keeping extraneous files from destination dirs. Because at default, we remove  extraneous files/dirs from destination dirs, so here we can use this option to avoid to remove these extraneous files.
> Dsync improve

- src/dsync/dsync.c
add the missing *contents* to long options array
> dsync: add the missing *contents* to long options array

- src/common/mfu_flist.c
- src/common/mfu_flist_walk.c
- src/dwalk/dwalk.c
dwalk should have been printing the summary to the screen by default.
The reason it was only happening when verbose was set was because
there were a couple of bugs in the mfu_flist_print_summary function.
MFU_LOG_INFO was not set by default, and it was requiring VERBOSE to
be set in order to use MFU_LOG_INFO log/print statements. So
mfu_flist_print_summary would print nothing unless the debug level
was set to VERBOSE. Also, mfu_flist_print_summary does not need
to be called in dwalk.c, because it is already called in mfu_flist_walk.
> Fix dwalk default output

- doc/rst/dcmp.1.rst
- src/dcmp/dcmp.c
Add option to dcmp to allow comparison of only metadata. If metadata
is the same, then contents are assumed to be the same. Similarly,
if the metadata is different, the contents are assumed to be
different. The lite mode does no comparison of data/content.
> dcmp lite mode

- src/dcmp/dcmp.c
This mode was not comparing the modification times correctly
in the compare function. It was mistakenly using the compare lists
instead of the original src and dst lists. The compare lists are
empty in lite mode and only used when comparing the contents of a
file.
> Fix dcmp lite mode metadata check

- experimental/dsh/dsh.c
- experimental/dtar/dtar.c
- src/common/mfu_flist.c
- src/common/mfu_flist.h
- src/common/mfu_flist_chmod.c
- src/common/mfu_flist_walk.c
- src/common/mfu_param_path.h
- src/dchmod/dchmod.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/ddup/ddup.c
- src/dfind/dfind.c
- src/drm/drm.c
- src/dstripe/dstripe.c
- src/dsync/dsync.c
- src/dwalk/dwalk.c
- Add remove option to drm
- Add mfu_walk_opts_t struct to hold
desired functionality during walk
- Pass walk_opts struct to
mfu_flist_walk_param_paths instead of
individual parameters (dir_perms & remove)
- Delete files in mfu_flist_walk for the
walk with stat and without
- Delete directories by level in drm
> drm: Add remove file capability during walk

- src/dreln/dreln.c
Missed updating dreln to use new walk_opts structure (silent merge conflict).
> dreln: update to use new walk_opts

- src/common/mfu_flist_copy.c
Setting the Lustre grouplock ID to zero by
default prevents errors when LUSTRE_SUPPORT
is available but NFS is the filesystem being
used.
> Set Lustre grouplock ID to zero by default

- configure.ac
- m4/lx_find_gpfs.m4
- src/common/mfu_flist_copy.c
We were interesting in using mpifileutils for copying data from one GPFS file-system to another however needed ACL support.
This patch adds support to enable `--enable-gpfs` to configure and adds calls to GPFS API `gpfs_getacl` and `gpfs_putacl` into `mfu_copy_permissions`.
Note that I have added include for `config.h` which was previously missing. There are bunch of `#ifdef LUSTRE_SUPPORT` lines already in the code, so adding config.h may have enabled some LUSTRE functionality? (I have no lustre systems to check this).
IBM docs on the API are at https://www.ibm.com/support/knowledgecenter/en/STXKQY_5.0.1/com.ibm.spectrum.scale.v5r01.doc/bl1adm_gpfs_getacl.htm
Code checks that when calling gpfs_getacl, 0 is returned - i.e. valid ACL had been collected, before attempting to write to …
> Add support for copying GPFS ACLs

- src/dcp/dcp.c
The boolean preserve field from the mfu_copy_opts
struct was being set to an integer (1) in dcp.
> Fix type error when setting preserve option in dcp

- doc/rst/build.rst
- spack.yaml
Spack views will soon get a feature upgrade, but in the mean time, these are the instructions for building the dependencies.
> spack build deps instructions

- src/dcmp/dcmp.c
Change the way differences between the source and
destination directories in dcmp are reported.
> update dcmp interface

- test/legacy/dcp1_tests/test_all.sh
- test/legacy/dcp1_tests/test_dcp1_many_dir_to_single_dir/test.sh
- test/legacy/dcp1_tests/test_dcp1_many_dir_to_single_file/test.sh
- test/legacy/dcp1_tests/test_dcp1_many_file_to_single_dir/test.sh
- test/legacy/dcp1_tests/test_dcp1_many_file_to_single_file/test.sh
- test/legacy/dcp1_tests/test_dcp1_single_dir_to_single_dir/test.sh
- test/legacy/dcp1_tests/test_dcp1_single_dir_to_single_file/test.sh
- test/legacy/dcp1_tests/test_dcp1_single_file_to_single_dir/test.sh
- test/legacy/dcp1_tests/test_dcp1_single_file_to_single_file/test.sh
Updated dcp1 tests scripts to use proper arguments for mpirun as
well as dcp1. The scripts were using many arguments that did not
exist anymore or had been changed/updated, which is why the tests
were failing. All tests for dcp1 pass now by running ./test_all
and setting two env variables.
> update old dcp1 tests

- src/dfind/dfind.c
Output looks like the following:
```
quartz2300{moody20}119: build/src/dfind/dfind
Usage: dfind [options] <path> EXPRESSIONS...
Options:
-i, --input <file>                      - read list from file
-o, --output <file>                     - write processed list to file
-v, --verbose                           - verbose output
-q, --quiet                             - quiet output
-h, --help                              - print usage
Tests:
--amin N       - last accessed N minutes ago
--anewer FILE  - last accessed more recently than FILE modified
--atime N      - last accessed N days ago
--cmin N       - status last changed N minutes ago
--cnewer FILE  - status last changed more recently than FILE modified
--ctime N      - status last changed N days ago
--mmin N       - data last modified …
```
> dfind: describe tests in help usage

- src/common/mfu_bz2_static.c
- src/common/mfu_compress_bz2_libcircle.c
- src/common/mfu_decompress_bz2_libcircle.c
- src/common/mfu_flist.h
- src/dcp1/common.h
These two commits fix the build problems I found while building mpifileutils in a recent openSUSE system.
> Build fixes

- doc/rst/dsync.1.rst
- src/common/mfu_flist.h
- src/common/mfu_flist_copy.c
- src/common/mfu_io.c
- src/common/mfu_io.h
- src/dsync/dsync.c
-l, --link-dest=DIR   - hardlink to files in DIR when unchanged
dsync -l /link_dest_dir/ /src/ /dst/
Signed-off-by: Gu Zheng <gzheng@ddn.com>
> dsync: add link-dest support

- doc/rst/dcp.1.rst
- src/dcp/dcp.c
- src/dcp1/dcp1.c
* always use braces
* no need for newline in MFU_LOG messages
* list options in consistent order between man page, print_usage, long opts, getopt string, and getopt while loop
* list verbose, quiet, and help as last options
* dcp: fix: have all ranks exit if chunksize/blocksize argument fails to parse
> dcp: style edits to chunk/block size options

- doc/rst/drm.1.rst
- src/drm/drm.c
Now that we have an --output option in drm, users may want full stat info to be recorded for each file from a walk.  This adds a new --stat option to enable stat during the walk.
> drm: add --stat to stat items during walk

- src/dchmod/dchmod.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/dreln/dreln.c
- src/drm/drm.c
- src/dstripe/dstripe.c
- src/dsync/dsync.c
Since progress messages will not be printed with --quiet mode of a tool, let's disable them from even happening which could save some MPI overhead.
> progress: disable progress messages with --quiet

- src/common/mfu_flist_copy.c
The default block_size in mfu_copy_opts will be set when creating a new object.  Someone may override that default, e.g., through the new --blocksize option in dcp.  We do not want to overwrite it during mfu_flist_copy back to the default.
> libmfu: do not overwrite block_size during flist_copy

- src/common/mfu_flist.h
- src/common/mfu_flist_copy.c
- src/dfilemaker1/dfilemaker1.c
This defines a new mfu_flist_fill() that will write random data to the files in an flist.  It is useful for using an flist to generate a set of files for testing.  We should generalize this to take an argument for the type of fill to be used, e.g., constant byte value, random, etc.
> mfu_flist_fill

- doc/rst/dcp.1.rst
- doc/rst/dsync.1.rst
- src/dsync/dsync.c
This adds a --sparse option to dsync, like in dcp, to copy sparse files.  With this option, it will attempt to read file extents if supported.  If not supported, it falls back to a regular read.  When writing, it will avoid writing blocks that are all 0.
> dsync: add --sparse option to copy sparse files

- src/common/mfu_flist_walk.c
When walking a large tree of empty directories using a --lite walk, the "Items walked" count can get stuck for a long time, so that it seems progress has stopped.
https://github.com/hpc/mpifileutils/issues/296
This changes the accounting so that we only include a directory in the count after we have read its contents, rather than when we first discover it.
> mfu: count directories after reading during walk

- src/common/mfu_compress_bz2_libcircle.c
Removed deprecated MPI-1.0 constructs, to ensure compatibility with Open MPI 4.x
https://www.open-mpi.org/faq/?category=mpi-removed
Signed-off-by: Kilian Cavalotti <kilian@stanford.edu>
> remove deprecated MPI-1.0 constructs

- doc/rst/dcmp.1.rst
- src/dcmp/dcmp.c
Documentation had some references to SRC_ONLY, DEST_ONLY, and ONLY_DST:
SRC_ONLY --> ONLY_SRC
DEST_ONLY --> ONLY_DEST
ONLY_DST --> ONLY_DEST
> docs: fix help to refer to ONLY_SRC and ONLY_DEST

- src/common/mfu_flist_chunk.c
In both dcmp and dsync --contents, a segmented scan is used in mfu_file_chunk_list_lor to identify files where different content has been detected.  The scan should segment the input based on a comparison of file names.  However, the file names were not being copied over from the chunk list, meaning the segmented scan was actually operating on an uninitialized set of bytes as returned by malloc.
In dcmp, this bug was discovered in reporting of false positives, i.e., reporting a file as being different when it was not.  A valid difference detected in some file early in the input array could spill into the flags corresponding to files later in the input array, if it so happened that the uninitialized file name happened to be the same.  This bug could also have prevented actual differences …
> mfu: fix invalid call to segmented scan

- doc/rst/dfind.1.rst
- src/common/mfu_pred.c
The check for MFU_PRED_TYPE() incorrectly used the file type as a
mask for the file mode, which would lead to collisions between types
e.g. S_IFREG (0100000) and S_IFLNK (0120000) or S_IFSOCK (0140000).
This would result in "-type f" also finding symlinks.
Properly use S_IFMT as the type mask for the file, and simplify the
return type since it is already a boolean when computed.
Update the man page to report -type can check for all file types.
Signed-off-by: Andreas Dilger <adilger@whamcloud.com>
> dfind: fix -type to allow all file types

- doc/rst/dchmod.1.rst
- doc/rst/libmfu.rst
- src/common/mfu_flist.h
- src/common/mfu_flist_chmod.c
- src/common/mfu_flist_walk.c
- src/dchmod/dchmod.c
* adds new chmod algorithm that avoids calling stat during walk when just setting the group or owner
* bug fix for deleting the linked list of permissions structs
* adds --force option to optionally force chown/chmod to be called on each item
* adds --silent option to avoid printing EPERM errors, which are common when changing files within a directory shared by different users
* adds logic to skip trying to change items whose owner uid is different from effective uid of process (normal users can't do this, privileged users can use --force)
* typos in libmfu documentation
* adds walk rate to walk progress messages
> dchmod: add algorithm to avoid stat during walk

- src/dbcast/dbcast.c
Some MPI functions in `dbcast.c` have been deprecated in MPI-2.0, and produce the following warning at compilation time (with Open MPI 4.0.1):
```
/dev/shm/mpifileutils-0.10/src/dbcast/dbcast.c: In function ‘gcs_get_shmem_file’:
/dev/shm/mpifileutils-0.10/src/dbcast/dbcast.c:218:5: warning: ‘MPI_Keyval_create’ is deprecated (declared at /share/software/user/open/openmpi/4.0.1/include/mpi.h:2695): MPI_Keyval_create was deprecated in MPI-2.0; use MPI_Comm_create_keyval instead. [-Wdeprecated-declarations]
MPI_Keyval_create(&gcs_shm_file_attr_copy, &gcs_shm_file_attr_del, &gcs_shm_file_key, (void*)0);
^
/dev/shm/mpifileutils-0.10/src/dbcast/dbcast.c:224:3: warning: ‘MPI_Attr_get’ is deprecated (declared at /share/software/user/open/openmpi/4.0.1/include/mpi.h:2675): MPI_Attr_get was …
```
> dbcast: replaced functions deprecated in MPI-2.0

- src/dfilemaker/dfilemaker.c
Give the user correct guidance about the relationship between
ntotal and nlevels.
The existing output is confusing:
```
bash-4.2$ dfilemaker --help                   
Usage: dfilemaker <nitems> <nlevels> <maxflen> [-i seed]
bash-4.2$ dfilemaker 5 4 3 
nfiles must be greater than nlevels
```
1. It refers to "nfiles" which is not the name of any of the arguments as described by dfilemaker
2. it doesn't indicate how nfiles is calculated
Signed-off-by: Olaf Faaland <faaland1@llnl.gov>
> correct usage message in dfilemaker

- src/common/mfu_flist_io.c
- src/common/mfu_flist_sort.c
Some MPI libraries do not support "external32" well, though "native" seems to be more widely available.  This adds some error checking around the MPI I/O calls in mfu_flist_io.c.  It prints an error message and aborts on any problem.
We also switch from external32 to native, hoping that will be more portable across MPI libraries.  Because with v4 of the mfu_flist file list format, we are handling all data conversion ourselves and then only writing MPI_BYTE, native should in theory work across all MPI libs (assuming none of them convert bytes in some way).
> mfu: switch from external32 to native mpi datarep, add error checks

- src/common/mfu_flist_copy.c
- src/common/mfu_io.c
When using O_DIRECT, different file systems have different requirements.  In general, one has to use aligned offsets within the file, aligned buffers in memory, and read/write counts that consist of an integral number of blocks.
The read count must always be an integral number of full blocks, even in the case where one knows that the file does not have that much data.  In this case, the read will simply return a short read.
Similarly when writing data, one may have to write past the end of a file by using a write count that exceeds the desired end of the file.  In that case, one must then truncate the file after it has been written.
To complicate matters further, one may be reading from a file system that requires one alignment block size but writing to a different file system that has a …
> mfu: always read full size blocks with O_DIRECT

- src/common/CMakeLists.txt
- src/common/mfu_errors.h
- src/common/mfu_io.c
- src/common/mfu_io.h
- src/common/mfu_param_path.c
- src/common/mfu_util.c
- src/common/mfu_util.h
- src/dcp/dcp.c
My branch deviated a bit from my previous PR, I had many small commits, and git wasn't cooperating, so I'm just creating a new PR entirely.
**common/mfu_errors.h**
- New file
- Defines some generic error codes, codes for dcp, and codes for DAOS
- Ranges are in the 1000s, 1100s, and 4000s
- Defines MFU_ERRF and MFU_ERRP for printing the error codes.
- Formatted as: MFU_ERR(#)
- Could be improved in the future to print the"string" error code instead of just MFU_ERR
- DAOS has something similar to this
**common/mfu_io**
- Defined daos_access
**common/mfu_param_path.c**
- mfu_param_path_check_copy - Return on DAOS error
**common/mfu_util**
- daos_connect
- Added flag for whether or not to connect to pool
- Added flag for whether or not to auto-create the destination container
- No longer …
> daos: dcp: enhanced error checking

- src/common/mfu_io.c
- src/common/mfu_util.c
- src/dcp/dcp.c
Three files, three commits:
**mfu_io.c**
_daos_mkdir_ - Fixed the sanity check against creating the root "/"
**mfu_util.c**
Added an include to remove a DAOS-related compile warning
**dcp.c**
Added a few more DAOS error cases.
Abstracted DAOS code into separate functions to simplify main()
closes #373 
closes #374
> daos: dcp: abstract and improve

- src/common/mfu_io.c
- src/common/mfu_io.h
daos_mknod is implemented in two steps:
1. dfs_open(..., O_CREATE,...)
2. dfs_release(...)
This works for regular files only at this time.
closes #377 
closes #353 
> daos: daos_mknod implementation

- src/common/mfu_flist_copy.c
- src/common/mfu_flist_walk.c
- src/common/mfu_io.c
- src/common/mfu_io.h
Three commits, three issues.
>**daos: mfu_file_unlink and daos_unlink implementation**
>Added implementation for mfu_file_unlink and daos_unlink.
>Updated mfu_flist_copy.c and mfu_flist_walk.c to use the
>new mfu_file_unlink.
>
>The following files still have references to mfu_unlink,
>but I don't believe that can/should be updated:
>mfu_flist_remove.c
>dbcast.c
>dreln.c
>copy.c
>dbz2.c
closes #352 
>**daos: mfu_io: add dfs_release for each dfs_lookup**
>Each daos_* function that uses dfs_lookup now also
>has a corresponding dfs_release, except for "open"
>functions, since this is handled in "close".
One exception: calls made in `lookup_insert_dir` do not have a corresponding `dfs_release`, since this will require more effort to fix. New issue #384 created to handle this.
closes #382 …
> daos: robust enhancements

- src/common/mfu_flist_walk.c
aarch64 kernel is not found SYS_getdents.
If SYS_getdents is not defined, use sys_getdents64.
Signed-off-by: Toyohisa Kameyama <kameyama@riken.jp>
> mfu: support aarch64

- src/common/mfu_flist_copy.c
- src/common/mfu_io.c
- src/common/mfu_param_path.h
- src/common/mfu_util.c
- src/common/mfu_util.h
- src/dcp/dcp.c
**_Question_** @adammoody
As the DAOS-related code grows, would you prefer we move DAOS-specific functions to some new `daos_util.[h,c]`? E.g. hash functions, setup functions.
(But keep the `daos_*` IO functions in `mfu_io.c`)
lookup_insert_dir and associated functions have been
refactored and expanded.
*mfu_param_path.h*
- Added dfs_hash to mfu_file.
- Removed only_daos from mfu_file, since it is no longer needed
*Naming convention*
- Changed mfu_* to daos_* since they are only used by DAOS.
- Changed lookup_insert_dir to daos_lookup_hash.
*daos_lookup_hash and associated functions*
- Gets the hash from mfu_file instead of a global.
- Uses a pointer to the name instead of static allocation,
which saves space.
- Updated error messages to use MFU_LOG instead of stderr directly.
- Added a …
> daos: enhance use of lookup hash

- src/common/mfu_flist_chunk.c
- src/common/mfu_flist_copy.c
- src/common/mfu_flist_walk.c
- src/common/mfu_io.c
- src/common/mfu_io.h
**_daos: added daos_symlink and daos_readlink_**
- Added `mfu_file_readlink`
- Added `daos_readlink`
- Added `mfu_file_symlink`
- Added `daos_symlink`
- Updated corresponding DAOS entry points
- Fixed bug with `PATH_MAX` check
closes #399 
**_mfu_copy_files: fixed memory leak with vals_**
Within `mfu_copy_files`, added `mfu_free(&vals)`
closes #393 
**_mfu_file_chunk_list_alloc: fixed memory leaks_**
Witin mfu_file_chunk_list_alloc:
Added mfu_free for each of the following:
- `sendlist`
- `recvlist`
- `heads`
- including nested linked list elements
- does not call `mfu_file_chunk_list_free`, because that also frees the `name`, which should not be freed here, because it points to the `mfu_flist` entry which should still be valid upon exiting
- `tails`
- `counts`
-`bytes`
- `sendbufs`
- …
> memory leaks and DAOS enhancements

- DAOS-Support.md
Update the Enable DAOS link in the DAOS-Support README.
> fix enable DAOS link in DAOS-Support README

- src/common/mfu_flist_copy.c
- src/common/mfu_io.c
- src/common/mfu_io.h
**mfu_io**
- Added `mfu_file_truncate`
- Added `daos_truncate`
**mfu_flist_copy.c**
- `mfu_copy_file_fiemap`
- Skip for DAOS src
- Not yet supported
- Skip if `ioctl` fails with `ENOTSUP`
- DAOS DFUSE-mounted path does not support this
- _**it seems that `cp` also silently ignores this**_
- Change `goto fail` to `goto fail_fiemap` for clarity
- Fixed some memory leaks for error conditions
- `goto fail_fiemap` instead of `goto fail_normal_copy`
- Changed an occurrence of `mfu_truncate` to `mfu_file_truncate`
> daos: gracefully handle failed fiemap

- DAOS-Support.md
- doc/rst/dcp.1.rst
- src/common/CMakeLists.txt
- src/common/mfu_util.c
- src/common/mfu_util.h
- src/dcp/dcp.c
The svcl is no longer required when connecting to
a DAOS pool, so it has been removed:
- Removed from DAOS-Support.md
- Removed from doc/rst/dcp.1.rst
- Removed from dcp.c
- Removed from mfu_util
Updated the shared libmfu.so major version,
based on previous changes and these changes.
closes #426 
> daos: remove svcl

- src/common/mfu_io.c
The DFS API has had support added for dereferencing
symlinks in dfs_lookup and dfs_lookup_rel.
- Removed daos_dereference_symlink
- No longer needed
- Modified calls to dfs_lookup_rel to pass O_NOFOLLOW when needed
- Modified daos_open to use dfs_lookup_rel
- Modified daos_opendir to use dfs_lookup_rel
> DAOS: Update I/O functions with O_NOFOLLOW

- src/common/mfu_util.c
A parameter is being removed from daos_pool_connect
in an upcoming version.
This conditionally compiles to work with both versions of daos.
> daos: conditional compile daos_pool_connect

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/common/mfu_flist.c
- src/common/mfu_flist.h
- src/common/mfu_flist_internal.h
- src/dcp/dcp.c
This adds support for copying any type of daos container
in parallel.
* add obj_id_lo and obj_id_hi to elem_t struct
* add total_oids field to flist
* add a pack and unpack call for obj_id_lo and obj_id_hi
* create mfu_flist_global_oid_size to return total oids
* add boolean is_posix_copy for non-posix copies
* adds daos_obj_copy function and helper functions
This copy starts by retrieving all obj ids on rank 0,
then it uses the mfu_flist_spread function to distribute
all obj ids evenly across ranks. After the obj ids are
distributed, the obj ids are copied using the local
flist.
Also, daos will split the anchor used to retrive all
obj ids and enumerate the dkeys, akeys, and records.
There is work that still needs to be done from the daos
level to split the anchor for the object iterator …
> daos: add support for copying daos containers at obj level

- .travis.yml
- CMakeLists.txt
- doc/rst/build.rst
libarchive 3.5.1 fixes some compile issues from 3.5.0.
I suggest using 3.5.1 in the documentation, etc. so other users don't run into compile issues that are fixed in 3.5.1.
> libarchive: update to version 3.5.1

- doc/rst/dcp.1.rst
- src/common/CMakeLists.txt
- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/common/mfu_flist_copy.c
- src/common/mfu_flist_walk.c
- src/common/mfu_io.c
- src/common/mfu_io.h
- src/common/mfu_param_path.c
- src/common/mfu_param_path.h
- src/dbz2/dbz2.c
- src/dchmod/dchmod.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/dcp1/handle_args.c
- src/dfind/dfind.c
- src/dreln/dreln.c
- src/drm/drm.c
- src/dsh/dsh.c
- src/dstripe/dstripe.c
- src/dsync/dsync.c
- src/dtar/dtar.c
- src/dwalk/dwalk.c
- `dcp`
- Added a missing daos_cleanup() call
- `mfu_param_path_set` and `mfu_param_path_set_all`
- Added the argument mfu_file
- Generally changed some functions to use the mfu_file
version, since mfu_file_t was introduced.
Also broke DAOS type into DFS and DAOS
- Changed previous usage of DAOS to DFS
- Added "new" DAOS for non-DFS API
- Added --daos-api to dcp
- Removed is_posix_copy references
- Use is_daos_copy locally in dcp
- Added compatibility checks for daos containers
- Refactored some DAOS functions
- Fixed memory leaks with setting argpaths
Closes #433 
> daos: improvements

- doc/rst/dcmp.1.rst
- doc/rst/dcp.1.rst
- doc/rst/dsync.1.rst
- src/common/mfu_daos.c
- src/common/mfu_flist.h
- src/common/mfu_flist_remove.c
- src/common/mfu_io.c
- src/common/mfu_io.h
- src/common/mfu_util.c
- src/common/mfu_util.h
- src/dcmp/dcmp.c
- src/drm/drm.c
- src/dsh/dsh.c
- src/dsync/dsync.c
Added daos support to dsync.
Added daos support to dcmp.
`dsync.c`
- Added daos options
- Modified IO calls to use `mfu_file_*`
`dcmp.c`
-- Added daos options
`mfu_io`
- Added `mfu_file_rmdir` and `daos_rmdir`
`mfu_flist_unlink`
- Added `mfu_file_t` param
`mfu_daos.c`
- Fixed error checking for DAOS args
> daos: dsync and dcmp support

- src/common/CMakeLists.txt
Bump shared library version to 3.0.0 due to previous commits.
> bump shared library version to 3.0.0

- src/dcmp/dcmp.c
- src/dsync/dsync.c
When splitting files into chunks, switch to slice files based on ``copy_opts->chunk_size`` instead of a hardcoded value of 1MB.  In addition to being more flexible and consistent, the hard coded value failed a self-imposed constraint when enabling O_DIRECT.
> dcmp, dsync: split on copy_opts chunk size rather than hardcoded value

- src/common/mfu_flist_copy.c
Fixed some compile warnings for shadowed variable declarations.
> fix compile warnings

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/dcp/dcp.c
- src/dsync/dsync.c
Abstracted some code from `dcp`.
Added very simple support to `dsync` for DAOS objects.
Improved some error handling in `dsync`.
Added supporting functions to `mfu_daos`.
Renamed some DAOS functions to use the prefix mfu_daos.
> daos dsync: simple DAOS object support

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-serialize/daos-serialize.c
Fixed a bug in daos_parse_path where -1 would
be returned for a POSIX path, but should be 1.
Simplified daos_parse_path to always require the daos://
prefix for daos paths.
Remove custom pool uuid parsing, which is now handled by
duns_resolve_path.
Improve some path free's.
> daos: simplify and enhance path parsing

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-deserialize/daos-deserialize.c
- src/daos-serialize/daos-serialize.c
Decrease the chunk size from 128MB to 1K.
This greatly reduces the space requirements.
> daos serialize: decrease chunk size

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/dcp/dcp.c
If daos-api=hdf5, then h5repack is invoked. This is for copying to/from DAOS HDF5 containers. If the daos-api flag is not set, then the default is to move hdf5 files to DAOS POSIX containers. Also, h5repack is serial, so if more than one rank is specified when an HDF5 container is the source or destination the program will exit with an error explaining only one process is supported currently.
> daos: copy hdf5 containers to and from POSIX filesystems

- src/common/mfu_daos.c
When creating a destination container,
create a POSIX type container when the source
is a POSIX path.
> daos: fix bug in cont create

- src/common/mfu_io.c
- src/common/mfu_param_path.c
- In `mfu_param_path_copy_dest`, don't cut the root path.
- In parse_filename, account for when dir and name are both "/",
which can happen depending on the version of basename used.
> daos: fix root path bug

- src/common/mfu_daos.c
- src/common/mfu_daos.h
Instead of creating a whole dataset for single value records,
just store the single value inside of the akey dataset. For
array record types this field is set to NULL, and the length
is set to zero.
> serialization optimizations: write single val to akey dset

- src/dcp/dcp.c
Don't try to perform a copy if the walk fails, since
the file list may be in an invalid state.
> daos dcp: don't try to copy if walk fails

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-serialize/daos-serialize.c
When creating a new DAOS container, copy the user attributes
and container properties from the src container.
> daos: copy user attrs and cont props on create

- .travis.yml
The "trusty' distro seems to be missing a public key.
The Travis documentation recommends not using Trusty, as it is EOL:
- https://docs.travis-ci.com/user/reference/trusty/
For reference, this is the difference:
- https://docs.travis-ci.com/user/reference/xenial/#differences-from-the-trusty-images
> travis: use default xenial instead of trusty

- src/common/mfu_daos.c
- src/common/mfu_errors.h
- src/common/mfu_flist_copy.c
- src/common/mfu_io.c
- src/common/mfu_io.h
- src/common/mfu_param_path.c
- src/common/mfu_param_path.h
- Replace the dfs_* IO calls with the new dfs_sys_* API.
- Return ENOSYS when not DAOS_SUPPORT.
- Added mfu_errno2rc to simplify returns from dfs_* calls.
> daos: use internal IO functions

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-deserialize/daos-deserialize.c
Remove copying of container label when copying from
DAOS->DAOS. The container label in DAOS is now required
to be unique. The container label is still serialized for
now until the API to check if container label already exists
in DAOS is available for use.
Only set container label on deserialization if it does not
exist.
Fix bug in cont_deserialize_all_props where a copy of the
pointer was being passed to it instead of the address to
the pointer, causing the properties to not be set correctly
in cont_create.
> daos: update setting of container label

- src/daos-deserialize/daos-deserialize.c
- src/daos-serialize/daos-serialize.c
daos-serialize was using a broadcast to report the rc code
on rank zero, which should be an Allreduce. Also, daos-deserialize
was printing serialize instead of deserialize when reporting an error.
> daos: cleanup error reporting in serialize and deserialize

- src/common/mfu_daos.c
The daos_cont_open_by_label was removed and is now
using daos_cont_open. Where a UUID or label can be
passed into the function.
> update daos_cont_open_by_label API call

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-serialize/daos-serialize.c
Check DAOS_PROP_CO_STATUS and do not serialize or copy
properties if status is unhealthy. Add force option
to serialize even if status is unhealthy, but never
copy with unhealthy status.
Serialize DAOS_PROP_CO_ROOTS and DAOS_PROP_CO_EC_CELL_SZ,
which were added after initial implementaion of
daos-serialize was completed. Also, remove calling of
dfs_cont_create in deserialization to avoid serialized
properties being overwritten. Since DFS API is not used
in serialization or deserialization it is better to instead
use daos_cont_create and pass in preserved properties to
the deserialization.
> daos: serialize new props and check cont status property

- src/common/mfu_flist_copy.c
Resolves https://github.com/hpc/mpifileutils/issues/494
> fix: use proper count in copy progress message

- doc/rst/dcmp.1.rst
- doc/rst/dcp.1.rst
- doc/rst/dsync.1.rst
- src/common/mfu_daos.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/dsync/dsync.c
This just removes the daos-prefix option from the documentation
because it is no longer necessary after a recent DAOS PR
that allows passing a subset of a UNS path to duns_resolve_path.
The option is removed from the documentation but not removed
from the code in order to preserve backwards compatibility with
the DAOS tests for the datamover.
The call to duns_resolve_path was updated in the case that the
last directory or file in the UNS path does not yet exist, since
it doesn't recurse the rest of the paths in the directory tree
in that case.
> daos: remove prefix from documentation and update call to duns_resolve_path

- src/common/mfu_daos.c
if dfs_sys_mount fails, don't call dfs_sys2base
> daos: remove duplicate error message

- doc/rst/dcp.1.rst
- doc/rst/dsync.1.rst
- src/common/mfu_flist_copy.c
- src/common/mfu_param_path.c
- src/common/mfu_param_path.h
- src/dcp/dcp.c
- src/dsync/dsync.c
- test/tests/test_dsync/test_xattr.py
- test/tests/test_dsync/test_xattr.sh
Rather than always copying xattrs, introduce a new option
"--xattrs | -e" to allow the user to control how this is done.
Options are
"none"        Copy no xattrs
"all"         Copy all xattrs (prior default)
"non-lustre"  Copy non-lustre xattrs (new default)
"libattr"        Copy xattrs not indicated as "skip" in /etc/xattr.conf
Copying xattrs is now independent of --preserve for owner, perms,
etc.
Lustre uses xattrs to record important information such as how the file
data should be distributed among the Lustre servers.  As a result,
copying the lustre xattrs prevents certain default values from taking
effect.
If "non-lustre" option is in effect, xattrs named in lustre
source file lustre_idl.h as of this writing are not synced (see
XATTR_NAME_SOM and friends).  In addition, xattrs with …
> dsync and dcp: allow user to control syncing of xattrs

- dist/CMakeLists.txt
- dist/README.dist
- dist/README.md
- dist/builddist
This adds a script to create a release tarball.  The tarball packages up mpiFileUtils along with the source for DTCMP, LWGRP, and libcircle all at appropriate release versions.  It compiles all source files into ``libmfu``.  This reduces the number of dependencies that a user has to install, it speeds up the build, and avoids errors due to version mismatches.
To build a release tarball:
```
cd dist
./builddist v0.11
```
Then to build:
```
tar -zxf mpifileutils-v0.11.tgz
pushd mpifileutils-v0.11
mkdir build
pushd build
make clean
cmake \
-DCMAKE_INSTALL_PREFIX=../install \
-DCMAKE_BUILD_TYPE=Debug \
-DCMAKE_VERBOSE_MAKEFILE=true \
-DENABLE_LUSTRE=ON \
-DENABLE_EXPERIMENTAL=ON \
-DWITH_LibArchive_PREFIX=/path/to/libarchive \
..
make -j install
```
In theory, libarchive could also be …
> WIP: add script to build release tarball

- dist/README.dist
- doc/rst/build.rst
- doc/rst/conf.py
- doc/rst/index.rst
This updates the build section of the documentation to describe how one builds from the release tarball.  That will simplify the build for most users.  The existing build process that describes how one builds from a clone of the repo is moved to a new development build section.
> doc: describe release build

- src/common/mfu_daos.c
Need to convert uuid_t to string then pass it to daos_cont_open().
> Daos api update API: daos_cont_open only supports uuid string.

- src/common/mfu_daos.c
Update more cases where daos_cont_open needs a string instead of UUID
> DAOS-9871 API: fix more daos_cont_open

- src/common/mfu_flist_copy.c
When executing a copy with ``O_DIRECT`` enabled, ``mfu_flist_copy()`` would hang if a file size had been reduced between the walk and the copy steps.
> fix: hang if file size shrinks during a copy

- .gitignore
- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/dsync/dsync.c
This was previously deprecated and is longer needed. The new way is to use a UNS path:
daos://pool/container/path/to/stuff
> daos: remove --daos-prefix handling

- src/common/mfu_param_path.c
Even when `! copy_into_dir`, we still still shouldn't cut the root component.
> mfu_param_path: fix cutting root component

- src/common/mfu_daos.c
Pass the correct permissions to daos_obj_open instead of 0.
> DAOS: use proper permissions for obj_open

- src/ddup/ddup.c
Resolves: https://github.com/hpc/mpifileutils/issues/556
> ddup: print file size warning with trailing newline

- doc/rst/dcmp.1.rst
- doc/rst/dcp.1.rst
- doc/rst/ddup.1.rst
- doc/rst/dsync.1.rst
- doc/rst/dtar.1.rst
- src/common/CMakeLists.txt
- src/common/mfu.h
- src/common/mfu_flist.h
- src/common/mfu_flist_archive.c
- src/common/mfu_flist_copy.c
- src/common/mfu_param_path.h
- src/common/mfu_proc.c
- src/common/mfu_proc.h
- src/common/mfu_util.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/ddup/ddup.c
- src/dsync/dsync.c
- src/dtar/dtar.c
This adds an ``--open-noatime`` option to a number of tools, which adds the ``O_NOATIME`` flag when opening files to avoid updating the file last access time.
Many centers use last access time to filter files for purge operations, and they would prefer not to change file atime values when making backup copies with ``dsync`` or scanning the file system for duplicate files with ``ddup``.  Adding this flag may also improve read performance on some file systems.
The ``O_NOATIME`` flag is only allowed when the effective user id matches the owner of the file or when the process is running with the ``CAP_FOWNER`` capability.  A normal user will encounter errors when using ``O_NOATIME`` when reading from a shared directory containing files owned by other users, even if the current user has read …
> mfu: add --open-noatime to open files with O_NOATIME

- src/common/mfu_flist.h
- src/common/mfu_flist_chmod.c
While adding the ``--open-noatime`` feature, it was discovered that ``mfu_flist_chmod`` was incorrectly checking for ``CAP_CHOWN`` and ``CAP_FOWNER`` capabilities.  The old check would have reported that a process had such capabilities when it did not.  This delegates the check to the new ``mfu_proc_set()`` function added for ``--open-noatime``.
> dchmod: fix check for CAP_CHOWN and CAP_FOWNER capabilities

- mpifileutils.spec
Documentation about these macros is available in Fedora project packaging guidelines:
https://docs.fedoraproject.org/en-US/packaging-guidelines/CMake/
One notable advantage of these macros is that they transparently define compiler and linker flags with distribution defaults.
> rpm: use %cmake macros

- src/common/mfu_daos.c
Addition of DAOS_PROP_CO_SCRUBBER_DISABLED property for serialization.
Signed-off-by: Ryon Jensen <ryon.jensen@intel.com>
> daos: support for additional container property

- src/dcp/dcp.c
When giving up privileges, setgroups should be called before setuid and/or setgid to avoid permission leaks.
Resolves #567
> dcp: call setgroups before setuid

- src/common/mfu_daos.c
- src/common/mfu_daos.h
- src/daos-serialize/daos-serialize.c
Open the source pool and container with RO, and the destination with RW.
> DAOS-14547: Source pool/cont only needs read permission

- src/dcp/dcp.c
When `--uid` or `--gid` is used, MPI_Init() is called as the original user. The original uid/gid is not being restored prior to calling MPI_Finalize(), which leads to cleanup issues.
Resolves #585.
> dcp: Restore UID/GID after setting with --uid/--gid

- test/tests/test_dsync/test_xattr.py
- test/tests/test_dsync/test_xattr.sh
Fixes two issues:
1. The command line generated in test_xattr.py to execute test_xattr.sh and run the test was wrong.  Fix that.
2. The output of "xattr -l" needs to be sorted for the xattr comparison to work consistently
Tested on lustre and xfs
> fixes to test_dsync/test_xattr.sh and test_dsync/test_xattr.py

- doc/rst/build.rst
The developer build instructions include some shell scripting to download, build, and install dependencies (e.g. libcircle, lwgrp).  That scripting assumes paths to dependency release tarballs that may be out-of-date.
If a dependency tarball download fails, tell the user which one failed and where to look, and do not proceed to building and installing.
After a release these docs may quickly become out-of-date, and so it can save some developer time to fail faster and give a clearer error message.
> build.rst shell script: stop if dependency download fails

- src/common/mfu_flist.h
- src/common/mfu_flist_walk.c
- src/dchmod/dchmod.c
- src/dcmp/dcmp.c
- src/dcp/dcp.c
- src/dfind/dfind.c
- src/dreln/dreln.c
- src/drm/drm.c
- src/dstripe/dstripe.c
- src/dsync/dsync.c
- src/dtar/dtar.c
- src/dwalk/dwalk.c
- test/tests/test_dsync/test_walkfail.sh
In dsync, if there was an error during the walk of the source tree, the source flist generated is likely incomplete.
In the case where the source and destination have the same files and directories before dsync --delete is run, an incomplete source flist results in files being incorrectly deleted from the destination.
When an error was detected for the source walk, warn the user and disable the --delete option.  Continue with the dsync, so that any new files identified are still copied and metadata is synced.
See rsync(1) for the --delete option, it takes the same approach.
Implement a test where dsync --delete is run, and the walk of the source tree is caused to fail by making a directory unreadable.
Before the patch, the test detects that files on the destination are deleted when they …
> dsync: disable --delete on src walk error

- src/common/mfu_flist_walk.c
- src/dsync/dsync.c
Fixes issues identified in the code review of #599
Since WALK_RESULT is an int and can only hold one error code, but any number of errors might be encountered during a walk, there is little value in recording errno.
In addition, the value of errno might have changed unless it is captured immediately after the library or system call that failed, which would require deeper code changes.
Instead, set to -1 as the indicator of a failure.
> mfu_flist_walk.c: set WALK_RESULT = -1

- .gitignore
Ignore the index file created by ctags.  The index file(s) created by cscope are already ignored as a side affect of an existing entry:
```
>   16 # Executables
>   17 *.exe
>>> 18 *.out
>   19 *.app
```
> .gitignore: ignore tags file created by ctags

- src/common/mfu_flist_copy.c
- src/dcp1/common.c
Initial buffer allocated is size 1204.  The intended size was 1024, indicated in the commit message (below).  1024 fits better in PAGE_SIZE and so may slightly improve memory management.
The typo was originally introduced into DCOPY_copy_xattrs(), then the code was copied into mfu_copy_xattrs() as part of later work.
The original commit that introduced the typo was:
commit 9a211b5f48f322d439b6f03dda6009dbff78e4c3
Author: Adam Moody <moody20@llnl.gov>
Date:   Thu Nov 21 14:19:59 2013 -0800
start out with 1024 byte buffer for xattrs
> fix bufsize typo in mfu_copy_xattrs and DCOPY_copy_xattrs

- src/dfilemaker/dfilemaker.c
* clarify file/dir/link counts per level
In debug output, when reporting file/dir/link counts, specify what level
of the generated tree those elements are at.
* add vim modeline
Add vim modeline to prevent introducing tabs instead of spaces,
by vim users.
* implement option --verbose/-v
Make default verbosity is MFU_LOG_WARN.
Each instance of -v in the options increases level up to MFU_LOG_DBG,
which is the maximum verbosity level.
* define options near print_usage()
Define the strings passed to getopt_long, short_options and
long_options, next to each other and next to print_usage() so
it's easier to ensure they stay synchronized with each other.
> dfilemaker: implement --verbose, add modelines, and refactor some code

- src/dfilemaker/dfilemaker.c
Commit
commit fc70c2ce3d7499685697157db91ccd645f2b031e
Author: Olaf Faaland <faaland1@llnl.gov>
Date:   Thu Nov 14 15:44:34 2024 -0800
dfilemaker: address review comments for PR #269
introduced an error.  mfu_free() takes a pointer to a pointer, because it both frees the memory, and also sets the pointer to NULL to prevent double-free bugs.
The above commit passed the address of the memory to be freed, not the address of the pointer.  This meant both that the wrong memory was freed, potentially, and also that the code attempted to set some arbitrary set of bytes to NULL.
In testing, this triggered a segfault when running dfilemaker.
> dfilemaker: pass correct pointer to mfu_free()

- src/dfilemaker/dfilemaker.c
(1) A duplicate longopts struct introduced during a rebase, when creating a PR to add
commit 1187ecf27e5ffb76b5a2ee0334d3b0925c0b32ff
Author: Olaf Faaland <faaland1@llnl.gov>
Date:   Thu Nov 21 16:19:03 2024 -0800
dfilemaker: define options near print_usage()
Define the strings passed to getopt_long, short_options and
long_options, next to each other and next to print_usage() so
it's easier to ensure they stay synchronized with each other.
Signed-off-by: Olaf Faaland <faaland1@llnl.gov>
(2) In addition, when adding support for "--verbose", some parts of the code
were changed from "version" to "verbose", but some were missed.
(3) If getopt_long() encounters an unknown option, print usage information
and stop execution.
Continuing to process options and create files, after encountering an …
> dfilemaker: exit on unrecognized option and remove duplicate longopts struct

- doc/rst/dwalk.1.rst
- man/dwalk.1
- src/common/mfu_flist.c
- src/common/mfu_flist_walk.c
- src/common/mfu_param_path.h
- src/dwalk/dwalk.c
This is a proposal to add --no-atime option on dwalk to not update the file last access time while doing a walk without stat.
The motivation behind this patch is that at CEA we have tools to administrate our filesystems and we want to use mpifileutils in these tools. We don't want the atime of a folder to be modified when admins walk a filesystem. For us, updating the atime is a user-side action and should therefore not be modified by our tools.
> Add option to not update the file last access time with dwalk

- test/tests/test_dsync/test_data.sh
- test/tests/test_dsync/test_existence.sh
- test/tests/test_dsync/test_expectfail.sh
- test/tests/test_dsync/test_metadata.sh
- test/tests/test_dsync/test_walkfail.sh
- test/tests/test_dsync/test_xattr.sh
Instead of using /usr/include/c++ as a source of test data, generate test data using dfilemaker.  There's no guarantee a machine being used for testing MFU will have /usr/include/c++ installed.
Remove TEST_TREE_DATA for test that does not use it.
Make first arg of the test_dsync tests, specify the MFU binary directory to use for testing, instead of specifying the path to dsync itself.
> test_dsync/test_existence.sh: use dfilemaker for test data

- test/tests/test_dsync/test_data.sh
Implement a test to verify checksums of the destination match those of the source, after dsync runs.
The first test runs dsync without any options, copying to an empty destination directory. It then calculates checksums for the files in source and destination, and verifies they match.
The second test creates data in source and destination directories, including files whose metadata match but whose data differ.  It then runs dsync without any options to verify no copies occur.  The process is roughly this:
- Create data in src
- Copy it to dest
- Change data in files in dest, without altering length
- Set timestamps on all files so they are the same
- Run dsync without --contents option
For all files, metadata should match but data should not match,
and no copies should occur.
The third …
> test_data.sh: add test to verify file contents

- src/dsync/dsync.c
Some file system do not support nanosecond part of the timespec for mtime (last modification time). We were comparing the mtime (tv_nsec nanosecond) regardless of the support to mtime nanosecond. This was causing dsync to add files to the copy to destination list even if the file were identical.
We added a check for source dir and destination dir to verify if the timepsec nanosecond (tv_nsec) was set to 0. In which case we do not compare the mtime nanosecond part of it (tv_nsec).
> Fix for issue dsync not updating times correctly #560.

- test/tests/test_dsync/test_multiple_syncs.sh
Test multiple dsyncs, and test dsync against rsync.
1. Running dsync twice, the second time no changes should be reported.
2. Running rsync followed by dsync, the dsync should report no changes.
3. Running dsync followed by rsync, the rsync should report no changes.
rsync is run with -av -HAX to copy hard links, ACLs, and xattrs.
However, the test data copied is created with dfilemaker, which does not create ACLs or xattrs, and may not create files with multiple hard links.  This should be improved.
> test_multiple_syncs.sh: verify sequential syncs change nothing

- src/common/mfu_util.c
- src/common/mfu_util.h
- src/dcmp/dcmp.c
- src/dsync/dsync.c
Update `dsync` and `dcmp` to detect a symlinks targets changes. In this case, the symlinks are reported to be different by `dcmp` and are updated by `dsync`.
Note this works for `dsync` both with or without `c, --contents`.
New function `mfu_compare_symlinks()` is introduced in library API to factorize the logic for all commands.
In order to reproduce the bug and validate the patch, I wrote this little script `symlink.sh`:
```sh
#!/bin/sh
DATA_DIR=../data
if [ -d ${DATA_DIR}/from ]; then
rm -r ${DATA_DIR}/from
fi
if [ -d ${DATA_DIR}/to ]; then
rm -r ${DATA_DIR}/to
fi
echo "→ Initialiazing testing data"
mkdir ${DATA_DIR}/from
echo foo > ${DATA_DIR}/from/file1
echo bar > ${DATA_DIR}/from/file2
ln -s file1 ${DATA_DIR}/from/link1
ln -s file2 ${DATA_DIR}/from/link2
echo
echo "→ Launching first …
```
> dsync/dcmp: support symlinks targets changes

- src/common/mfu_flist_archive.c
Fix creation of corrupted archive with symlink when --preserve-{xattrs,acl,flags} command line option is used.
When it is provided a valid file descriptor, libarchive archive_read_disk_entry_from_file() calls fstat() which follows symlinks. This commit introduces an exception for symlinks to not provide a file descriptor to archive_read_disk_entry_from_file() which makes it call lstat() on entry path and create a valid symlink archive entry eventually.
fix #628
> dtar: fix creation with symlink and --preserve-*

- dist/CMakeLists.txt
- dist/builddist
Added mfu_proc.c to libmfu as it is now used across all tools
Fixed the builddist script by putting the right current version tag
> Fixing the build distribution for the tar file
