hpc/mpifileutils

test/tests/test_dcp/checkfiemap.c
test/tests/test_dcp/test_fiemap.py
test/tests/test_dcp/test_fiemap.sh

Signed-off-by: Gu Zheng <gzheng@ddn.com>

test : add test case for dcp against FIEMAP

---

experimental/dsh/dsh.c

I just added a print default of 25 to the print_sums function, and an extra print line that says how many of the total number of items are being printed/displayed.

added dsh print default

---

experimental/dsh/dsh.c

Summary of updates:
1) bump print_default from 25 to 100
2) print the whole list if print_default == -1, otherwise print minimum of print_default and allcount
3) print the value of allcount in "top 100 of ..." message instead of allsum_count, and print this as an unsigned long long

dsh-print-updates

---

index.html

Updated the repo name (as many places as I could find).

Rename website from fileutils -> mpifileutils

---

index.html

Our mailing list is now at groups.google.com/mpiFileUtils.

Update the mailing list.

---

m4/lx_find_lustre.m4

build: do lustre available check only if --enable-lustre is set

---

src/common/mfu_flist.h
src/common/mfu_flist_io.c

To satisfy request to write file list to text file.  The final version should allocate a smaller write buffer to not use too much memory.  Also, it would be nice to provide an interface to allow caller to customize fields and formats used when writing data.

mfu: write flist to text file

---

src/dstripe/dstripe.c

Thanks for the suggestion, @adilger .

dstripe: call rename, rather than unlink + rename

---

src/drm/drm.c

Fix and improve some of the messages in drm's usage() command.

Fix drm usage() messages

---

.travis.yml
buildme_dependencies
buildme_dependencies.git
experimental/dsh/dsh.c
src/dcmp/dcmp.c

DTCMP changed the interface to its segmented exclusive scan function in v1.1.0.

update to dtcmp v1.1.0

---

src/dfilemaker/dfilemaker.c
src/dfmake/dfmake.c

Latest dfmake.c and dfilemaker.c

new dfmake.c and dfilemaker.c

---

src/common/mfu_flist_copy.c
src/common/mfu_flist_usrgrp.c

- fix bug surfaced on sierra with reading cache files
- improve error messages
- fix so dsync will create target directory if it doesn't exist

fix bugs turned up on sierra testing

---

src/common/mfu_flist.c
src/common/mfu_flist.h
src/common/mfu_flist_chmod.c
src/common/mfu_flist_chunk.c
src/common/mfu_flist_copy.c
src/common/mfu_flist_create.c
src/common/mfu_flist_io.c
src/common/mfu_flist_remove.c
src/common/mfu_flist_sort.c
src/common/mfu_flist_walk.c
src/common/mfu_param_path.c
src/common/mfu_util.c
src/common/mfu_util.h
src/dcmp/dcmp.c
src/dsync/dsync.c

Currently deletes such files, but that will be changed to either optionally delete or simply report.

Report files for which a portion failed to copy

---

.github/CONTRIBUTING.md
README.md

- Fix broken link to contributor document
- Provide example Signed-off-by text

fix broken link to contributor docs

---

src/common/mfu_flist_io.c
src/common/mfu_util.h
src/dcmp/dcmp.c
src/dfind/dfind.c
src/drm/drm.c
src/dwalk/dwalk.c

- drops rank and file/line info from log messages for non-error and non-debug levels
- adds timing log messages when writing output to text format
- fixes bug when computing buffer size during output

fixes for a few issues turned up in testing

---

AUTHORS

Adding Ahana to AUTHORS list for dbz2 contribution.

AUTHORS: add Ahana Roy Choudhury

---

src/dbcast/dbcast.c

This should solve https://github.com/hpc/mpifileutils/issues/251

dbcast: avoid testing write access on target dirs, change to MFU_LOG msgs

---

.travis.yml

This PR formalizes our documented contributing guidance and checks that the commit has a "Signed-off-by:" line in the last commit message.

verify signoff with travis

---

AUTHORS

Add me (Gu Zheng) into AUTHORS
Signed-off-by: Gu Zheng <gzheng@ddn.com>

Add me (Gu Zheng) into AUTHORS

---

src/dbcast/dbcast.c
src/dchmod/dchmod.c
src/dcmp/dcmp.c
src/dcp/dcp.c
src/ddup/ddup.c
src/drm/drm.c
src/dstripe/dstripe.c
src/dsync/dsync.c
src/dwalk/dwalk.c

This cherry-picks a bunch of commits from @levatin1 and puts them into the same branch. Supersedes  #258

Direct users to online man pages in print_usage

---

doc/rst/build.rst

build: add gpfs and powerpc notes

---

.travis.yml

Signed-off-by: Elsa Gonsiorowski (Uranus) <gonsiorowski1@llnl.gov>

add make install to travis

---

src/common/mfu_util.c

When out of memory, try using more nodes!
Signed-off-by: Elsa Gonsiorowski (Hylonome)

malloc error message

---

doc/rst/dbz2.1.rst
doc/rst/dchmod.1.rst
doc/rst/dfind.1.rst
src/dbz2/dbz2.c
src/dchmod/dchmod.c
src/dcmp/dcmp.c
src/dcp/dcp.c
src/ddup/ddup.c
src/dfind/dfind.c
src/drm/drm.c
src/dstripe/dstripe.c
src/dsync/dsync.c
src/dwalk/dwalk.c

I've reviewed all the released tools to make sure the help text, man pages, and option parsing matches. Fixes #272.

Review of Tool Option Documentation

---

doc/rst/dreln.1.rst
src/dreln/dreln.c

dreln: add progress messages

---

src/dstripe/dstripe.c

dstripe: replace printf with MFU_LOG

---

doc/rst/dchmod.1.rst
src/common/mfu_flist_chmod.c
src/dchmod/dchmod.c

dchmod: support uid and gid in --owner and --group options

---

src/common/mfu_flist_copy.c

* eliminate some GPFS ACL debug messages, since verbosity was increased in earlier commit
* change messages to errors
* avoid printing messages if either source or destination are not GPFS
* return error if source and destination are GPFS but ACL copy fails
* move ACL copy logic to mfu_copy_acls() and only copy ACL when -p is thrown
* fix for buffer size bug when original ACL buffer is too small

gpfs: acl copy messages and return codes

---

src/common/mfu_progress.c

The non-root processes would initiate a reduce after 10 seconds but would then reset a timer to wait another 10 seconds before checking that it was done.  This causes the first progress message to be printed after 20 seconds instead of 10.  The fix here is to always test the reduce/bcast in each update call, but only start a new bcast after each 10 second time out.

progress: test reduce/bcast in non-root on each update call

---

doc/rst/dsync.1.rst
src/dsync/dsync.c

dsync: link-dest edits

---

.travis.yml
doc/rst/dwalk.1.rst
src/common/mfu_flist_remove.c
src/common/mfu_flist_walk.c
src/dcp1/dcp1.c
src/dtar/mfu_flist_archive.c
src/dwalk/dwalk.c

update libcircle to use termination tree and reduction period calls

---

doc/rst/build.rst
doc/rst/index.rst
man/dbcast.1
man/dbz2.1
man/dchmod.1
man/dcmp.1
man/dcp.1
man/ddup.1
man/dfind.1
man/dreln.1
man/drm.1
man/dstripe.1
man/dsync.1
man/dwalk.1
man/mpifileutils.1
mpifileutils.spec

docs: update to libcircle-v0.3, move design goals to front

---

src/common/mfu_compress_bz2_libcircle.c
src/common/mfu_decompress_bz2_libcircle.c
src/dcp1/handle_args.c

eliminate multiple definitions of global variables

---

src/common/mfu_util.c
src/common/mfu_util.h
src/dcp/dcp.c

daos: style updates

---

src/common/mfu_flist_copy.c
src/common/mfu_io.c
src/common/mfu_param_path.h

Fixes for issue #350 and #351 

daos cleanup

---

DAOS-Support.md
README.md
doc/rst/build.rst

Adds documentation about DAOS Support as well as instructions for enabling DAOS when building MpiFileUtils.

Add documentation about DAOS Support

---

src/dcp/dcp.c

Previously you could only provide one service level to DAOS,
but we should be able to pass a service level for the
source and destination pools explicitly.

Add option for daos-dst-svcl

---

doc/rst/index.rst

add link to overview talk

---

src/dcp/dcp.c

daos_set_paths now properly allows a UNS path on the
source or destination when the other uses a prefix.
Details in #365.

Refined daos_set_paths to allow UNS on src and dst

---

src/dsync/dsync.c

Signed-off-by: Honwai Leong <hleong@ddn.com>

dsync: add Direct IO support to dsync; speed up metadata updates. 

---

src/common/mfu_flist_walk.c

Makes it easier to see where the problem is...

Print name of path that is deemed too long.

---

doc/rst/build.rst

doc: update build steps to use libarchive-3.5.0

---

.travis.yml
src/dtar/dtar.c

dtar: add missing arg to mfu_param_path_set

---

DAOS-Support.md

Updating the DAOS-Support document to reflect recent interface changes for DAOS in mpifileutils. Also, shows examples for copying data at the OBJ level, for non-POSIX containers. 

Update DAOS-Support.md doc with new interface examples

---

src/common/mfu_flist_archive.c

I happened to try dtar on a boost tar file, which contains a sequence of consecutive EOF / empty archives at the end of the main archive.  This fixes the scan logic to account for that.

mfu: improve archive scan to handle multiple EOF markers

---

DAOS-Support.md
README.md
doc/rst/build.rst

Fixed some errors in the documentation.
Added more examples.
closes #464 

daos: update documentation

---

src/common/mfu_flist_walk.c

The main motivation for this is that DAOS often has root paths "/", since that is the root of a container. When the paths are built, this happens:
```
dir = "/"
name = "something"
path = "//something"
```
Although DAOS/DFS handles the double "//", it creates a slight performance and caching problem.
The path building was also modified to use snprintf, which is more performant. Even with the additional "/" check, this should should be _**slightly**_ faster.

mfu_flist_walk: handle trailing slash in dirname

---

doc/rst/dfind.1.rst
src/common/mfu_daos.c
src/common/mfu_daos.h
src/dcmp/dcmp.c
src/dcp/dcp.c
src/dfind/dfind.c
src/drm/drm.c
src/dsync/dsync.c
src/dwalk/dwalk.c

- Add support to drm for DAOS POSIX containers.
- Add support to dfind for DAOS POSIX containers.
- Add support to daos internals for a single path.

daos: drm, dfind, and dwalk support

---

src/common/mfu_daos.c
src/daos-serialize/daos-serialize.c

Fixes some valgrind errors in daos-serialize.

valgrind fixes for daos-serialize

---

src/common/mfu_daos.c

object format will be changed since 2.0, this patch
adds codes to be aware of new changes.
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

daos: fix to support new DAOS api

---

src/common/mfu_daos.c
src/daos-gen/daos-gen.c

- Fix daos-gen compilation
- Fix error message in mfu_daos.c

DAOS: fix daos-gen compilation

---

src/common/mfu_bz2_static.c
src/common/mfu_compress_bz2_libcircle.c
src/common/mfu_daos.c
src/common/mfu_decompress_bz2_libcircle.c
src/common/mfu_flist.c
src/common/mfu_flist_chmod.c
src/common/mfu_flist_copy.c
src/common/mfu_flist_create.c
src/common/mfu_flist_walk.c

remove many, but not all, instances of unused variables.

remove unused variables

---

CONTRIBUTING.md

Google group forum does not exist

readme: Remove google group

---

src/daos-gen/daos-gen.c

daos_obj_generate_oid() API is updated a little bit. Conditional compiling code are added for several other functions recently updated too.
Signed-off-by: Lei Huang <lei.huang@intel.com>

daos-9200 daos-gen: Fix compatible code for API update.

---

src/common/mfu_daos.c

Signed-off-by: Lei Huang <lei.huang@intel.com>

DAOS-9902 API: To support empty container lable

---

doc/rst/dcp.1.rst
src/dcp/dcp.c

Signed-off-by: Blake Devcich <blake.devcich@hpe.com>

dcp: Added options (-G, -U) to set effective GID/UID to perform copy

---

src/dsync/dsync.c

By adding this check we can avoid hours of source walk to find out the destination is (RO) read only.

Added a test to verify destination parent to avoid long source walk

---

src/dfilemaker/dfilemaker.c

In some cases MPI_Finalize() and similar teardown
functions were called before exit, and in other cases they were not.
In addition, in many cases the exit code was 0 even though we were exiting due to an error condition.
When an error is identified during option parsing or other tasks in main(), exit with a meaningful error code and use the same code for cleanup prior to exiting.
When an error is encountered elsewhere, exit with a useful error code.

dfilemaker: exit in a consistent manner

---

src/dfilemaker/dfilemaker.c

Instead of creating files in the current working directory by default, require the user to provide a path to the parent directory under which files, directories, and links will be created.
This makes it explicit what file system will be affected.
It's a frequent issue on LC computers that users accidentally run parallel tasks on NFS file systems which aren't able to handle the load, degrading service for everyone.
It's also sometimes the case that users run a utility without any arguments expecting a usage message.  With the old behavior, that would result in a large directory tree being created in a directory the user didn't intend.
This change addresses both of these issues.

dfilemaker: add parent_path positional argument

---

.gitlab-ci.yml
scripts/prepmfubuild.sh

- Added .gitlab-ci.yml workflow for pipeline
- Added scripts/prepmfubuild.sh build process

Added CI/CD work for llnl testing

---

src/common/mfu_flist_copy.c

ftruncate is expensive on many file systems. Avoid calling truncate in unecessary situation like when using O_DIRECT but the file size is what is expected, or when not using O_DIRECT. The logic is implemented as follows with dcp:
create file
if EEXIST:
stat file
if sparse or file size > bytes we will write:
truncate file to 0
write data
if O_DIRECT:
stat file
if file size > truncate offset:
truncate file to truncate offset

dcp: avoid truncate when not needed
